### ISSUE TITLE
when running epoch0, the index suddenly became very big.

### ISSUE THREAD

**Issue by YiliaZhu** [Dohppak/EMOPIA_cls#9]
sir, I'm trying to train the `wav domain classification` model from scratch.  When I run with `python train_test.py --wav sr22k --task ar_va`, an error is reported: `IndexError: single positional indexer is out-of-bounds`. 

So I navigator to the `data.py`, use `print(f'index={index}')` to observe the situation:
![86HS0_ATPBBWD@5`0U8R1HG](https://user-images.githubusercontent.com/86595820/171224000-79858e14-dd94-43b0-bcb4-7e30e130e733.png)

Then I run `train_test.py` again. Below I pasted the full display of the error report. I found that when running epoch0, the index suddenly became very big. This is what caused the  error. I don't know how to solve it.

------------------------------------------------------------------------------------------------------------------------------------------

![9ASMOJZSH2}4V(1(%107~$B](https://user-images.githubusercontent.com/86595820/171218692-9d1cd74e-ae6c-4c93-9f7d-1dbe47bf6a46.png)

Validation sanity check:   0%|                                                                   | 0/1 [00:00<?, ?it/s]index = 0
index = 1
index = 2
index = 3
index = 4
index = 5
index = 6
index = 7
index = 8
index = 9
index = 10
index = 11
index = 12
index = 13
index = 14
index = 15
index = 16
index = 17
index = 18
index = 19
index = 20
index = 21
index = 22
index = 23
index = 24
index = 25
index = 26
index = 27
index = 28
index = 29
index = 30
index = 31
Global seed set to 42
Epoch 0:   0%|                                                                                   | 0/9 [00:00<?, ?it/s]index = 1088
Traceback (most recent call last):
  File "train_test.py", line 183, in <module>
    main(args)
  File "train_test.py", line 135, in main
    trainer.fit(runner, datamodule=pipeline)  
  File "C:\Users\24061\anaconda3\envs\emopia\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 463, in fit
    self._run(model)
  File "C:\Users\24061\anaconda3\envs\emopia\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 761, in _run
    self.dispatch()
  File "C:\Users\24061\anaconda3\envs\emopia\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 802, in dispatch
    self.accelerator.start_training(self)
  File "C:\Users\24061\anaconda3\envs\emopia\lib\site-packages\pytorch_lightning\accelerators\accelerator.py", line 96, in start_training
    self.training_type_plugin.start_training(trainer)
  File "C:\Users\24061\anaconda3\envs\emopia\lib\site-packages\pytorch_lightning\plugins\training_type\training_type_plugin.py", line 144, in start_training
    self._results = trainer.run_stage()
  File "C:\Users\24061\anaconda3\envs\emopia\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 812, in run_stage
    return self.run_train()
  File "C:\Users\24061\anaconda3\envs\emopia\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 874, in run_train
    self.train_loop.run_training_epoch()
  File "C:\Users\24061\anaconda3\envs\emopia\lib\site-packages\pytorch_lightning\trainer\training_loop.py", line 491, in run_training_epoch
    for batch_idx, (batch, is_last_batch) in train_dataloader:
  File "C:\Users\24061\anaconda3\envs\emopia\lib\site-packages\pytorch_lightning\profiler\profilers.py", line 112, in profile_iterable
    value = next(iterator)
  File "C:\Users\24061\anaconda3\envs\emopia\lib\site-packages\pytorch_lightning\trainer\supporters.py", line 530, in prefetch_iterator
    last = next(it)
  File "C:\Users\24061\anaconda3\envs\emopia\lib\site-packages\pytorch_lightning\trainer\supporters.py", line 464, in __next__
    return self.request_next_batch(self.loader_iters)
  File "C:\Users\24061\anaconda3\envs\emopia\lib\site-packages\pytorch_lightning\trainer\supporters.py", line 478, in request_next_batch
    return apply_to_collection(loader_iters, Iterator, next)
  File "C:\Users\24061\anaconda3\envs\emopia\lib\site-packages\pytorch_lightning\utilities\apply_func.py", line 85, in apply_to_collection
    return function(data, *args, **kwargs)
  File "C:\Users\24061\anaconda3\envs\emopia\lib\site-packages\torch\utils\data\dataloader.py", line 530, in __next__
    data = self._next_data()
  File "C:\Users\24061\anaconda3\envs\emopia\lib\site-packages\torch\utils\data\dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "C:\Users\24061\anaconda3\envs\emopia\lib\site-packages\torch\utils\data\dataloader.py", line 1250, in _process_data
    data.reraise()
  File "C:\Users\24061\anaconda3\envs\emopia\lib\site-packages\torch\_utils.py", line 457, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\24061\anaconda3\envs\emopia\lib\site-packages\torch\utils\data\_utils\worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\24061\anaconda3\envs\emopia\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\24061\anaconda3\envs\emopia\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\24061\Desktop\MERcode\EMOPIA_cls-main\emopia_retrain\audio_cls\src\data.py", line 34, in __getitem__
    audio_fname = self.fl.iloc[index].name
  File "C:\Users\24061\anaconda3\envs\emopia\lib\site-packages\pandas\core\indexing.py", line 1767, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "C:\Users\24061\anaconda3\envs\emopia\lib\site-packages\pandas\core\indexing.py", line 2137, in _getitem_axis
    self._validate_integer(key, axis)
  File "C:\Users\24061\anaconda3\envs\emopia\lib\site-packages\pandas\core\indexing.py", line 2062, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds

index = 9415
index = 9102
wandbindex = 6822
: Waiting for W&B process to finish... (failed 1). Press Ctrl-C to abort syncing.
index = 9948
index = 2649
index = 698101 MB of 0.001 MB uploaded (0.000 MB deduped)
index = 3089
wandb:
wandb: Synced playful-thunder-62: https://wandb.ai/yiliazhu/uncategorized/runs/wiq17y5e
wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: .\wandb\run-20220531_235944-wiq17y5e\logs

**Comment by YiliaZhu** [comment]
I have solved this problem.This error is caused by the mismatch of torch, torchvision and torchaudio. And some of my mistakes.
